//! Determinized Monte-Carlo search for the Expert and Enoch difficulty tiers.
//!
//! This is a wall-clock-capped, single-observer determinized search over the
//! trick phase. For the acting player's candidate moves (generated by the
//! engine's legal-move generators and pruned by a [`Policy`]), we:
//!
//! 1. Sample N plausible worlds (full hands for every seat) consistent with the
//!    redacted view — see [`crate::bot::determinize`]. We NEVER look at the real
//!    hidden hands; determinization is the only window into them.
//! 2. In each world, apply the candidate move on a *cloned* engine play-phase,
//!    then play the trick out (and a short greedy continuation) using the
//!    [`Policy`] as the rollout policy for every seat.
//! 3. Score the resulting position from the acting player's team's perspective
//!    (points captured + a positional bonus) and average over worlds.
//!
//! We then pick the candidate with the best average value. The whole thing is
//! time-boxed with [`std::time::Instant`]: when the budget is exhausted we stop
//! sampling and return the best estimate so far, so a slow CPU degrades to fewer
//! simulations rather than hanging.
//!
//! # Policy source (heuristic vs net prior) — AlphaZero-lite
//!
//! [`SearchConfig`] carries TWO [`Policy`] knobs:
//!
//! * `policy` — the candidate **prior** at the root: how the legal candidates are
//!   ranked and pruned to the top-K the search then evaluates.
//! * `rollout_policy` — the policy that picks **rollout** moves for every seat
//!   inside each determinized world.
//!
//! The heuristic-prior search sets both to [`Policy::Heuristic`] (the
//! hand-written Shengji backbone — also Expert's net-load fallback prior).
//! Expert sets the *prior* to [`Policy::Net`] (the distilled learned net from
//! [`crate::bot::expert`]) while keeping heuristic rollouts. The net is a far
//! stronger ROOT PRIOR than it is a cheap deep-rollout policy — a net call per
//! ply starves the time-boxed search of worlds, and the net's myopic single-shot
//! picks add little once we are already deep in a hypothetical line — so it is
//! used where it pays off (selecting which candidates to search) and the fast
//! heuristic drives the many rollout plies. Either [`Policy::Net`] use falls back
//! to the heuristic whenever the net can't score a position.
//!
//! The leaf value is still the static [`evaluate_position`] (the net is a policy,
//! not a value net), so this is "search + a learned policy prior" — AlphaZero-
//! lite. Both tiers share the determinizer, world sampling, rollout machinery,
//! and leaf evaluator below; only the prior differs, so Expert (search + learned
//! prior) can beat the heuristic-prior search on the same compute.

use std::time::{Duration, Instant};

use rand::rngs::StdRng;
use rand::{Rng, SeedableRng};

use shengji_mechanics::types::{Card, PlayerID};

use crate::bot::determinize::sample_hidden_hands;
use crate::bot::expert;
use crate::bot::heuristics::{self, ScoredPlay};
use crate::game_state::play_phase::PlayPhase;

/// The policy source that supplies the candidate prior (for pruning) and the
/// rollout moves inside the determinized search.
///
/// `Heuristic` is the hand-written backbone. `Net` is the learned Expert
/// net used as the policy prior + rollout policy; it always falls back to the
/// heuristic when the net can't score a position, so a `Net` search is never
/// worse-behaved than a `Heuristic` one.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Policy {
    /// The hand-written Shengji heuristic.
    Heuristic,
    /// The distilled learned net (Expert tier), heuristic fallback.
    Net,
    /// The hand-written heuristic with the Enoch full-game playbook layered on
    /// (Enoch tier). Same machinery as [`Policy::Heuristic`] but the lead/follow
    /// scorers add the Enoch-specific bonuses, so the Enoch playbook shapes BOTH
    /// the root candidate prior and the rollout moves.
    EnochHeuristic,
}

/// Tunable search parameters.
#[derive(Clone, Copy, Debug)]
pub struct SearchConfig {
    /// Wall-clock budget for a single decision.
    pub time_budget: Duration,
    /// Maximum number of candidate moves to evaluate (top-K by heuristic).
    pub max_candidates: usize,
    /// Maximum number of determinized worlds to sample per decision.
    pub max_worlds: usize,
    /// How many tricks (× players) of look-ahead each rollout plays before the
    /// static evaluation. Deeper rollouts give a more accurate value at higher
    /// cost.
    pub rollout_tricks: usize,
    /// RNG seed (lets the eval harness make runs reproducible).
    pub seed: u64,
    /// Which policy supplies the candidate **prior** at the root — i.e. how the
    /// legal candidates are ranked and pruned to the top-K that the search then
    /// evaluates. The learned net (Expert) is a strong prior here; the heuristic
    /// is the heuristic baseline (also Expert's net-load fallback prior).
    pub policy: Policy,
    /// Which policy chooses the **rollout** moves for every seat inside each
    /// determinized world. Decoupled from `policy` because the net is a far
    /// better *root prior* than it is a cheap deep-rollout policy: a net call per
    /// ply starves the search of worlds and the net's myopic single-shot picks
    /// add little once we are already deep in a hypothetical line. Expert
    /// therefore uses `Policy::Net` as the prior but `Policy::Heuristic` for the
    /// (many, cheap) rollout plies — search + a learned policy prior, AlphaZero-
    /// lite, with a fast default rollout policy.
    pub rollout_policy: Policy,
}

impl Default for SearchConfig {
    fn default() -> Self {
        // Mirrors the strengthened in-game Expert/Enoch search (see
        // `crate::bot::policy::Knobs` / `search_budget_ms`): a deeper, off-lock
        // determinized search masked by the bot's ~1200ms visible pacing. Nothing
        // on the live path constructs the config via `default()` — the policy
        // builds it explicitly from the per-tier knobs — so this just keeps the
        // documented default aligned with production.
        SearchConfig {
            time_budget: Duration::from_millis(2200),
            max_candidates: 6,
            max_worlds: 144,
            rollout_tricks: 12,
            seed: 0xC0FFEE,
            policy: Policy::Heuristic,
            rollout_policy: Policy::Heuristic,
        }
    }
}

/// Run the determinized search and return the chosen cards, or `None` if no
/// candidate could be produced (caller should fall back to the heuristic /
/// dumb policy).
pub fn search_play(p: &PlayPhase, me: PlayerID, config: SearchConfig) -> Option<Vec<Card>> {
    // Candidate generation + policy pruning: rank by the configured policy (net
    // prior for Expert, playbook/heuristic for Enoch) and take the top-K.
    let mut candidates: Vec<ScoredPlay> = ranked_candidates(p, me, config.policy);
    if candidates.is_empty() {
        return None;
    }
    candidates.truncate(config.max_candidates.max(1));

    // If there's only one candidate, no need to search.
    if candidates.len() == 1 {
        return Some(candidates.remove(0).cards);
    }

    let mut rng = StdRng::seed_from_u64(config.seed);

    let mut totals = vec![0.0f64; candidates.len()];
    let mut counts = vec![0u32; candidates.len()];

    let start = Instant::now();
    let mut worlds_done = 0;

    'outer: while worlds_done < config.max_worlds {
        if start.elapsed() >= config.time_budget {
            break;
        }
        // Sample one world; reuse it across all candidates for a fair, paired
        // comparison (variance reduction).
        let world = match sample_hidden_hands(p, me, &mut rng) {
            Some(w) => w,
            None => {
                worlds_done += 1;
                continue;
            }
        };

        for (idx, cand) in candidates.iter().enumerate() {
            // Periodically re-check the time budget so a heavy world can't blow
            // the cap.
            if start.elapsed() >= config.time_budget {
                break 'outer;
            }
            let value = evaluate_candidate(
                &world.play,
                me,
                &cand.cards,
                config.rollout_tricks,
                config.rollout_policy,
                &mut rng,
            );
            if let Some(v) = value {
                totals[idx] += v;
                counts[idx] += 1;
            }
        }
        worlds_done += 1;
    }

    // Pick the candidate with the best average value; break ties toward the
    // higher heuristic score (candidates are already heuristic-sorted, so the
    // earliest index wins ties).
    let mut best_idx = 0;
    let mut best_avg = f64::NEG_INFINITY;
    for idx in 0..candidates.len() {
        let avg = if counts[idx] > 0 {
            totals[idx] / counts[idx] as f64
        } else {
            // No simulations ran for this candidate; fall back to its heuristic
            // score so it isn't unfairly ignored.
            candidates[idx].score
        };
        if avg > best_avg {
            best_avg = avg;
            best_idx = idx;
        }
    }

    Some(candidates[best_idx].cards.clone())
}

/// Run a PERFECT-INFORMATION search and return the chosen cards, or `None` if no
/// candidate could be produced (caller should fall back to the heuristic / dumb
/// policy).
///
/// # Perfect information (Omniscient cheater tier ONLY)
///
/// Unlike [`search_play`], this does NOT sample hidden hands. The play phase `p`
/// passed in is the TRUE world — every seat's real cards — because it was
/// obtained for an `Omniscient` bot via the centralized honesty bypass
/// ([`crate::bot::observed_state`]). We therefore evaluate every candidate
/// against that single known world using full (un-truncated) rollouts, with no
/// ε-noise and no softmax temperature (greedy on the search value). This reuses
/// exactly the same machinery ([`evaluate_candidate`] → [`rollout`] →
/// [`evaluate_position`]) as the honest determinized search; only the world source
/// differs (one true world vs. many sampled worlds).
///
/// This is the only search entry point that reads the real opponents' hands, and
/// it is reachable solely through the `Omniscient` dispatch in
/// [`crate::bot::policy`].
pub fn search_play_perfect_info(
    p: &PlayPhase,
    me: PlayerID,
    config: SearchConfig,
) -> Option<Vec<Card>> {
    let mut candidates: Vec<ScoredPlay> = ranked_candidates(p, me, config.policy);
    if candidates.is_empty() {
        return None;
    }
    candidates.truncate(config.max_candidates.max(1));
    if candidates.len() == 1 {
        return Some(candidates.remove(0).cards);
    }

    let mut rng = StdRng::seed_from_u64(config.seed);

    // Evaluate each candidate against the SINGLE true world `p`. We can run a few
    // rollouts per candidate (the rollout policy carries a little noise, so
    // averaging a handful reduces variance) within the time budget, then pick the
    // best mean value greedily (no ε, no temperature).
    let start = Instant::now();
    let mut best_idx = 0;
    let mut best_avg = f64::NEG_INFINITY;
    for (idx, cand) in candidates.iter().enumerate() {
        let mut total = 0.0f64;
        let mut count = 0u32;
        for _ in 0..config.max_worlds.max(1) {
            if start.elapsed() >= config.time_budget {
                break;
            }
            if let Some(v) = evaluate_candidate(
                p,
                me,
                &cand.cards,
                config.rollout_tricks,
                config.rollout_policy,
                &mut rng,
            ) {
                total += v;
                count += 1;
            }
        }
        let avg = if count > 0 {
            total / count as f64
        } else {
            cand.score
        };
        if avg > best_avg {
            best_avg = avg;
            best_idx = idx;
        }
    }

    Some(candidates[best_idx].cards.clone())
}

/// Rank the legal candidates for `me` under the given [`Policy`] (best first).
///
/// For [`Policy::Heuristic`] this is exactly the heuristic ranking. For
/// [`Policy::Net`] we generate the same legal candidate set and order it by a
/// BLEND of the learned net's per-candidate distribution and the heuristic's
/// (the learned policy prior, regularized by the hand heuristic — see the inline
/// comment). If the net can't run (model missing/failed, or fewer than two
/// candidates), we transparently fall back to the heuristic ranking, so the
/// search is never starved of candidates.
fn ranked_candidates(p: &PlayPhase, me: PlayerID, policy: Policy) -> Vec<ScoredPlay> {
    let leading = p.trick().played_cards().is_empty();

    let heuristic_ranked = || -> Vec<ScoredPlay> {
        if leading {
            heuristics::ranked_leads(p, me)
        } else {
            heuristics::ranked_follows(p, me)
        }
    };

    match policy {
        Policy::Heuristic => heuristic_ranked(),
        Policy::EnochHeuristic => {
            if leading {
                heuristics::ranked_leads_enoch(p, me)
            } else {
                heuristics::ranked_follows_enoch(p, me)
            }
        }
        Policy::Net => {
            // Generate the legal candidates the net should rank.
            let cands: Vec<Vec<Card>> = if leading {
                heuristics::lead_candidates(p, me)
            } else {
                heuristics::follow_candidates(p, me)
            };
            if cands.len() < 2 {
                // 0 or 1 candidate: nothing for the net to discriminate; defer to
                // the heuristic ranking (which also handles its own fallbacks).
                return heuristic_ranked();
            }
            let net_scores = match expert::score_candidates_net(p, me, &cands) {
                Some(s) => s,
                // Net unavailable: fall back to the heuristic prior.
                None => return heuristic_ranked(),
            };
            // BLENDED prior: rank by a convex mix of the net's per-candidate
            // probability and the heuristic's, rather than the net alone. The
            // distilled net and the hand heuristic make *different* mistakes; each
            // is on its own ~as good a prior as the other, but mixing them yields a
            // strictly more informed candidate ordering — which is what lets the
            // net-guided Expert search edge out the heuristic-only search on
            // the same compute. Both signals are squashed to a comparable [0,1]
            // softmax distribution so neither's raw scale dominates.
            let ctx = heuristics::EvalCtx::build(p, me);
            let heur_scores: Vec<f64> = cands
                .iter()
                .map(|c| {
                    if leading {
                        heuristics::score_lead(&ctx, p, c)
                    } else {
                        heuristics::score_follow(&ctx, p, c)
                    }
                })
                .collect();
            let net_probs = softmax(&net_scores.iter().map(|&s| s as f64).collect::<Vec<_>>());
            let heur_probs = softmax(&heur_scores);
            // Weight: lean on the net (the distilled teacher signal) but keep a
            // meaningful heuristic contribution so its complementary strengths
            // (e.g. crisp end-game / trump-conservation rules) survive.
            const NET_W: f64 = 0.6;
            const HEUR_W: f64 = 0.4;
            let mut scored: Vec<ScoredPlay> = cands
                .into_iter()
                .enumerate()
                .map(|(i, cards)| ScoredPlay {
                    cards,
                    score: NET_W * net_probs[i] + HEUR_W * heur_probs[i],
                })
                .collect();
            scored.sort_by(|a, b| {
                b.score
                    .partial_cmp(&a.score)
                    .unwrap_or(std::cmp::Ordering::Equal)
            });
            scored
        }
    }
}

/// Numerically-stable softmax over a slice of scores, returning a probability
/// distribution of the same length. An empty input yields an empty vector. Used
/// to put the net and heuristic candidate scores on the same [0,1] scale before
/// blending them into the search prior.
fn softmax(scores: &[f64]) -> Vec<f64> {
    if scores.is_empty() {
        return Vec::new();
    }
    let max = scores.iter().copied().fold(f64::NEG_INFINITY, f64::max);
    if !max.is_finite() {
        // All -inf (e.g. empty candidates scored): uniform.
        let u = 1.0 / scores.len() as f64;
        return vec![u; scores.len()];
    }
    let exps: Vec<f64> = scores.iter().map(|&s| (s - max).exp()).collect();
    let sum: f64 = exps.iter().sum();
    if sum <= 0.0 || !sum.is_finite() {
        let u = 1.0 / scores.len() as f64;
        return vec![u; scores.len()];
    }
    exps.into_iter().map(|e| e / sum).collect()
}

/// Apply `cards` for `me` in a clone of `world`, then roll the rest of the
/// position out with `policy` and return the position value from `me`'s team's
/// perspective. Returns `None` if the candidate is somehow illegal in this world
/// (it should be legal, since it was generated from the redacted hand, which is
/// a subset of this world).
fn evaluate_candidate(
    world: &PlayPhase,
    me: PlayerID,
    cards: &[Card],
    rollout_tricks: usize,
    policy: Policy,
    rng: &mut StdRng,
) -> Option<f64> {
    let mut sim = world.clone();
    // Play our candidate.
    if sim.play_cards(me, cards).is_err() {
        return None;
    }

    // Roll out a bounded number of tricks with `policy` as every seat's policy,
    // then statically evaluate. Deeper look-ahead (`rollout_tricks`) yields a
    // more accurate value at higher cost; the static evaluator credits the
    // trick-winning potential still in our hand so we don't have to play every
    // card to value the position.
    let players = sim.propagated().players().len();
    // `saturating_mul` so a `rollout_tricks` of `usize::MAX` (the Omniscient
    // "roll out the whole hand" sentinel) caps at `usize::MAX` plies instead of
    // overflowing; the rollout loop terminates anyway once the hand is finished.
    let max_plies = players.saturating_mul(rollout_tricks.max(1));
    rollout(&mut sim, max_plies, policy, rng);

    Some(evaluate_position(&sim, me))
}

/// Choose the rollout move for `actor` under `policy`, returning the ranked
/// candidate list (best first) so the caller can fall back to lower-ranked plays
/// if the top pick is illegal in this determinized world.
///
/// For [`Policy::Net`] we order the legal candidates by the learned net (the
/// policy-guided rollout); if the net can't score this position we fall back to
/// the heuristic ranking. `Policy::Heuristic` always uses the heuristic ranking.
fn rollout_ranked(
    sim: &PlayPhase,
    actor: PlayerID,
    leading: bool,
    policy: Policy,
) -> Vec<Vec<Card>> {
    let heuristic_cards = || -> Vec<Vec<Card>> {
        let ranked = if leading {
            heuristics::ranked_leads(sim, actor)
        } else {
            heuristics::ranked_follows(sim, actor)
        };
        ranked.into_iter().map(|s| s.cards).collect()
    };

    match policy {
        Policy::Heuristic => heuristic_cards(),
        Policy::EnochHeuristic => {
            let ranked = if leading {
                heuristics::ranked_leads_enoch(sim, actor)
            } else {
                heuristics::ranked_follows_enoch(sim, actor)
            };
            ranked.into_iter().map(|s| s.cards).collect()
        }
        Policy::Net => {
            let cands: Vec<Vec<Card>> = if leading {
                heuristics::lead_candidates(sim, actor)
            } else {
                heuristics::follow_candidates(sim, actor)
            };
            if cands.len() < 2 {
                return heuristic_cards();
            }
            match expert::score_candidates_net(sim, actor, &cands) {
                Some(scores) => {
                    let mut idx: Vec<usize> = (0..cands.len()).collect();
                    idx.sort_by(|&a, &b| {
                        scores[b]
                            .partial_cmp(&scores[a])
                            .unwrap_or(std::cmp::Ordering::Equal)
                    });
                    idx.into_iter().map(|i| cands[i].clone()).collect()
                }
                None => heuristic_cards(),
            }
        }
    }
}

/// Greedily roll the play-phase forward using `policy` for whichever seat is to
/// act, finishing tricks as needed, for up to `max_plies` card plays. Mutates
/// `sim` in place.
fn rollout(sim: &mut PlayPhase, max_plies: usize, policy: Policy, rng: &mut StdRng) {
    use rand::seq::SliceRandom;

    let mut plies = 0;
    while plies < max_plies {
        if sim.game_finished() {
            break;
        }
        match sim.trick().next_player() {
            None => {
                // Trick complete: finish it (winner leads next).
                if sim.finish_trick().is_err() {
                    break;
                }
            }
            Some(actor) => {
                let leading = sim.trick().played_cards().is_empty();
                let mut ranked = rollout_ranked(sim, actor, leading, policy);
                if ranked.is_empty() {
                    break;
                }
                // Use the policy-best move, with a small amount of noise so
                // rollouts explore (paired worlds already share the deal).
                let pick = if ranked.len() > 1 && rng.gen_bool(0.15) {
                    // occasionally take the 2nd-best to add variance
                    ranked.remove(1)
                } else {
                    ranked.remove(0)
                };
                let mut cards = pick;
                // Defensive: if the chosen play is somehow illegal in this
                // determinized world, fall back to any legal candidate.
                if sim.play_cards(actor, &cards).is_err() {
                    // Try other candidates.
                    let alts = if leading {
                        heuristics::lead_candidates(sim, actor)
                    } else {
                        heuristics::follow_candidates(sim, actor)
                    };
                    let mut ok = false;
                    let mut alts = alts;
                    alts.shuffle(rng);
                    for alt in alts {
                        if sim.play_cards(actor, &alt).is_ok() {
                            cards = alt;
                            ok = true;
                            break;
                        }
                    }
                    if !ok {
                        break;
                    }
                }
                let _ = cards;
                plies += 1;
            }
        }
    }
}

/// Static evaluation of a play-phase position from `me`'s team's perspective.
///
/// Combines the realized point differential so far (the non-landlord point total
/// is what the scoring engine ultimately uses) with a positional term crediting
/// the *trick-winning potential* still in our hand. Because rollouts are
/// shallow, the positional term is what lets the search prefer plays that
/// preserve our ability to capture future point tricks rather than only chasing
/// immediate points.
fn evaluate_position(sim: &PlayPhase, me: PlayerID) -> f64 {
    use shengji_mechanics::types::{Card, EffectiveSuit, Number};

    let team = sim.landlords_team();
    let me_is_landlord_team = team.contains(&me);

    // `calculate_points` returns (non_landlord_points, observed). The defending
    // (landlord) team wants non_landlord_points LOW; the attacking team wants it
    // HIGH. We orient the score so HIGHER is always better for `me`'s team.
    let (non_landlord_points, _) = sim.calculate_points();
    let realized = if me_is_landlord_team {
        -(non_landlord_points as f64)
    } else {
        non_landlord_points as f64
    };

    // Positional control: high cards and trumps remaining in our own hand are
    // future trick winners. Value them so the search keeps control rather than
    // dumping winners prematurely.
    let trump = sim.trump();
    let control = sim
        .hands()
        .get(me)
        .map(|h| {
            let mut v = 0.0;
            for (card, &ct) in h.iter() {
                let c = *card;
                let is_trump = trump.effective_suit(c) == EffectiveSuit::Trump;
                let mut w = 0.0;
                match c {
                    Card::BigJoker | Card::SmallJoker => w = 1.6,
                    Card::Suited { number, .. } => {
                        if is_trump {
                            w = 0.8;
                        } else if number == Number::Ace {
                            w = 1.0;
                        } else if number == Number::King {
                            w = 0.5;
                        }
                    }
                    Card::Unknown => {}
                }
                v += w * ct as f64;
            }
            v
        })
        .unwrap_or(0.0);

    realized + control
}
