//! Determinized Monte-Carlo search for the Expert and Enoch difficulty tiers.
//!
//! This is a wall-clock-capped, single-observer determinized search over the
//! trick phase. For the acting player's candidate moves (generated by the
//! engine's legal-move generators and pruned by a [`Policy`]), we:
//!
//! 1. Sample N plausible worlds (full hands for every seat) consistent with the
//!    redacted view — see [`crate::bot::determinize`]. We NEVER look at the real
//!    hidden hands; determinization is the only window into them.
//! 2. In each world, apply the candidate move on a *cloned* engine play-phase,
//!    then play the trick out (and a short greedy continuation) using the
//!    [`Policy`] as the rollout policy for every seat.
//! 3. Score the resulting position from the acting player's team's perspective.
//!    A schema-v2 model supplies signed level-utility V when available; otherwise
//!    the mechanics-aware static evaluator is used. Candidate Q can also blend
//!    into the root prior/final estimate behind calibration gates.
//!
//! We then pick the candidate with the best average value. The whole thing is
//! time-boxed with [`std::time::Instant`]: when the budget is exhausted we stop
//! sampling and return the best estimate so far, so a slow CPU degrades to fewer
//! simulations rather than hanging.
//!
//! # Policy source (heuristic vs net prior) — AlphaZero-lite
//!
//! [`SearchConfig`] carries TWO [`Policy`] knobs:
//!
//! * `policy` — the candidate **prior** at the root: how the legal candidates are
//!   ranked and pruned to the top-K the search then evaluates.
//! * `rollout_policy` — the policy that picks **rollout** moves for every seat
//!   inside each determinized world.
//!
//! The heuristic-prior search sets both to [`Policy::Heuristic`] (the
//! hand-written Shengji backbone — also Expert's net-load fallback prior).
//! Expert sets the *prior* to [`Policy::Net`] (the distilled learned net from
//! [`crate::bot::expert`]) while keeping heuristic rollouts. The net is a far
//! stronger ROOT PRIOR than it is a cheap deep-rollout policy — a net call per
//! ply starves the time-boxed search of worlds, and the net's myopic single-shot
//! picks add little once we are already deep in a hypothetical line — so it is
//! used where it pays off (selecting which candidates to search) and the fast
//! heuristic drives the many rollout plies. Either [`Policy::Net`] use falls back
//! to the heuristic whenever the net can't score a position.
//!
//! Schema-v2 artifacts may expose separate policy, signed level-V, and action-Q
//! semantics. Each head is shape/manifest checked and independently gated; a
//! legacy policy-only artifact continues to use the static leaf and heuristic Q
//! fallback. An optional default-off belief proposal biases only hard-legal
//! hidden-card assignments.

use std::collections::HashSet;
use std::sync::OnceLock;
use std::time::{Duration, Instant};

use rand::rngs::StdRng;
use rand::{Rng, SeedableRng};

use shengji_mechanics::types::{Card, PlayerID};

use crate::bot::determinize::DeterminizedWorld;
use crate::bot::endgame::{self, ExactEndgameConfig, ExactValueAttempt};
use crate::bot::expert;
use crate::bot::heuristics::{self, ScoredPlay};
use crate::game_state::play_phase::PlayPhase;

fn sample_world<R: Rng>(p: &PlayPhase, me: PlayerID, rng: &mut R) -> Option<DeterminizedWorld> {
    crate::bot::belief::sample_persistent_world(p, me, rng)
}

/// The policy source that supplies the candidate prior (for pruning) and the
/// rollout moves inside the determinized search.
///
/// `Heuristic` is the hand-written backbone. `Net` is the learned Expert
/// net used as the policy prior + rollout policy; it always falls back to the
/// heuristic when the net can't score a position, so a `Net` search is never
/// worse-behaved than a `Heuristic` one.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Policy {
    /// The hand-written Shengji heuristic.
    Heuristic,
    /// The distilled learned net (Expert tier), heuristic fallback.
    Net,
    /// The hand-written heuristic with the Enoch full-game playbook layered on
    /// (Enoch tier). Same machinery as [`Policy::Heuristic`] but the lead/follow
    /// scorers add the Enoch-specific bonuses, so the Enoch playbook shapes BOTH
    /// the root candidate prior and the rollout moves.
    EnochHeuristic,
}

/// Tunable search parameters.
#[derive(Clone, Copy, Debug)]
pub struct SearchConfig {
    /// Wall-clock budget for a single decision.
    pub time_budget: Duration,
    /// Maximum number of candidate moves to evaluate (top-K by heuristic).
    pub max_candidates: usize,
    /// Maximum number of determinized worlds to sample per decision.
    pub max_worlds: usize,
    /// How many tricks (× players) of look-ahead each rollout plays before the
    /// static evaluation. Deeper rollouts give a more accurate value at higher
    /// cost.
    pub rollout_tricks: usize,
    /// RNG seed (lets the eval harness make runs reproducible).
    pub seed: u64,
    /// Which policy supplies the candidate **prior** at the root — i.e. how the
    /// legal candidates are ranked and pruned to the top-K that the search then
    /// evaluates. The learned net (Expert) is a strong prior here; the heuristic
    /// is the heuristic baseline (also Expert's net-load fallback prior).
    pub policy: Policy,
    /// Which policy chooses the **rollout** moves for every seat inside each
    /// determinized world. Decoupled from `policy` because the net is a far
    /// better *root prior* than it is a cheap deep-rollout policy: a net call per
    /// ply starves the search of worlds and the net's myopic single-shot picks
    /// add little once we are already deep in a hypothetical line. Expert
    /// therefore uses `Policy::Net` as the prior but `Policy::Heuristic` for the
    /// (many, cheap) rollout plies — search + a learned policy prior, AlphaZero-
    /// lite, with a fast default rollout policy.
    pub rollout_policy: Policy,
}

impl Default for SearchConfig {
    fn default() -> Self {
        // Mirrors the strengthened in-game Expert/Enoch search (see
        // `crate::bot::policy::Knobs` / `search_budget_ms`): a deeper, off-lock
        // determinized search masked by the bot's ~1200ms visible pacing. Nothing
        // on the live path constructs the config via `default()` — the policy
        // builds it explicitly from the per-tier knobs — so this just keeps the
        // documented default aligned with production.
        SearchConfig {
            time_budget: Duration::from_millis(2200),
            max_candidates: 6,
            max_worlds: 144,
            rollout_tricks: 12,
            seed: 0xC0FFEE,
            policy: Policy::Heuristic,
            rollout_policy: Policy::Heuristic,
        }
    }
}

/// Whether per-decision search tracing is enabled (env `SHENGJI_SEARCH_TRACE`,
/// any non-empty value other than "0"). Read ONCE and cached, so the hot search
/// path pays nothing when it is off. When on, [`search_play`] logs, per decision,
/// the candidate count, worlds completed vs the cap, wall-clock spent vs the
/// budget, and whether the decision was TIME- or WORLDS-bound — the diagnostic
/// that answers whether the production budget is actually being exhausted (see
/// `docs/bot-training-roadmap.md`, the 1-day plan).
fn search_trace_enabled() -> bool {
    static ENABLED: OnceLock<bool> = OnceLock::new();
    *ENABLED.get_or_init(|| {
        std::env::var("SHENGJI_SEARCH_TRACE")
            .map(|v| !v.is_empty() && v != "0")
            .unwrap_or(false)
    })
}

/// The leaf-evaluator learned-VALUE blend weight (env `SHENGJI_VALUE_WEIGHT`,
/// clamped to `[0, 1]`; default **0.0 = OFF**, so [`evaluate_position`] is exactly
/// the static eval and production behavior is unchanged until a value-head model
/// is trained and this knob is set). Read ONCE and cached. When `> 0` and a
/// 2-output value model is loaded, the leaf eval becomes
/// `(1-w)·static + w·net_value`. See `docs/bot-training-roadmap.md` (1-month plan).
fn value_weight() -> f64 {
    static W: OnceLock<f64> = OnceLock::new();
    *W.get_or_init(|| {
        std::env::var("SHENGJI_VALUE_WEIGHT")
            .ok()
            .and_then(|v| v.parse::<f64>().ok())
            .map(|w| w.clamp(0.0, 1.0))
            .unwrap_or(0.0)
    })
}

/// Schema-v2 models predict the actual normalized hand objective (win plus level
/// advancement), not point margin. When such a typed model is loaded, use its
/// state-V as a replacement leaf objective instead of mixing incompatible units.
/// The opt-out is useful for ablations; legacy/embedded models are unaffected.
fn level_value_leaf_enabled() -> bool {
    static ENABLED: OnceLock<bool> = OnceLock::new();
    *ENABLED.get_or_init(|| {
        let enabled = std::env::var("SHENGJI_LEVEL_VALUE_LEAF")
            .map(|value| !value.is_empty() && value != "0")
            .unwrap_or(true);
        enabled
            && matches!(
                expert::loaded_model_semantics(),
                Some(
                    expert::ExpertModelSemantics::V2LevelValue
                        | expert::ExpertModelSemantics::V2LevelQ
                )
            )
    })
}

/// Weight of a calibrated schema-v2 Q(o,a) prediction in the final root choice.
/// Both rollout means and Q are min-max normalized across the same candidate set,
/// so no point/level units are mixed. Constant Q is ignored rather than allowing
/// card-key tie order to replace the established policy/search signal.
fn q_blend_weight() -> f64 {
    static WEIGHT: OnceLock<f64> = OnceLock::new();
    *WEIGHT.get_or_init(|| {
        std::env::var("SHENGJI_Q_BLEND")
            .ok()
            .and_then(|value| value.parse::<f64>().ok())
            .map(|value| value.clamp(0.0, 1.0))
            .unwrap_or(0.35)
    })
}

/// Whether the determinized search uses PUCT/UCB simulation allocation instead of
/// flat per-world averaging (env `SHENGJI_SEARCH_PUCT`, non-empty & != "0"; default
/// OFF). Read ONCE and cached, so the flat path pays nothing when it's off.
fn puct_enabled() -> bool {
    static E: OnceLock<bool> = OnceLock::new();
    *E.get_or_init(|| {
        std::env::var("SHENGJI_SEARCH_PUCT")
            .map(|v| !v.is_empty() && v != "0")
            .unwrap_or(false)
    })
}

/// Adaptive budgets are deliberately opt-in. The configured `time_budget` stays
/// an absolute deadline; this feature only returns unused time on routine,
/// low-uncertainty decisions and can never make a decision slower.
#[derive(Clone, Copy, Debug)]
struct AdaptiveBudgetConfig {
    enabled: bool,
    min_fraction: f64,
}

fn adaptive_budget_config() -> AdaptiveBudgetConfig {
    static CONFIG: OnceLock<AdaptiveBudgetConfig> = OnceLock::new();
    *CONFIG.get_or_init(|| AdaptiveBudgetConfig {
        enabled: std::env::var("SHENGJI_ADAPTIVE_BUDGET")
            .map(|value| !value.is_empty() && value != "0")
            .unwrap_or(false),
        min_fraction: std::env::var("SHENGJI_ADAPTIVE_BUDGET_MIN_FRACTION")
            .ok()
            .and_then(|value| value.parse::<f64>().ok())
            .filter(|value| value.is_finite())
            .map(|value| value.clamp(0.05, 1.0))
            .unwrap_or(0.35),
    })
}

/// Empirical lower-tail risk controls. Defaults are exactly risk-neutral. This
/// works with every existing leaf (static or learned) because it operates on the
/// distribution of determinized-world/rollout returns, not on a new model shape.
#[derive(Clone, Copy, Debug)]
struct RiskConfig {
    stddev_penalty: f64,
    cvar_weight: f64,
    cvar_alpha: f64,
}

impl RiskConfig {
    fn enabled(self) -> bool {
        self.stddev_penalty > 0.0 || self.cvar_weight > 0.0
    }
}

fn risk_config() -> RiskConfig {
    static CONFIG: OnceLock<RiskConfig> = OnceLock::new();
    *CONFIG.get_or_init(|| RiskConfig {
        stddev_penalty: std::env::var("SHENGJI_SEARCH_STDDEV_PENALTY")
            .ok()
            .and_then(|value| value.parse::<f64>().ok())
            .filter(|value| value.is_finite())
            .map(|value| value.clamp(0.0, 4.0))
            .unwrap_or(0.0),
        cvar_weight: std::env::var("SHENGJI_SEARCH_CVAR_WEIGHT")
            .ok()
            .and_then(|value| value.parse::<f64>().ok())
            .filter(|value| value.is_finite())
            .map(|value| value.clamp(0.0, 1.0))
            .unwrap_or(0.0),
        cvar_alpha: std::env::var("SHENGJI_SEARCH_CVAR_ALPHA")
            .ok()
            .and_then(|value| value.parse::<f64>().ok())
            .filter(|value| value.is_finite())
            .map(|value| value.clamp(0.01, 1.0))
            .unwrap_or(0.25),
    })
}

/// Exact solving is also opt-in and hard-capped a second time in `endgame`.
fn exact_endgame_config() -> ExactEndgameConfig {
    static CONFIG: OnceLock<ExactEndgameConfig> = OnceLock::new();
    *CONFIG.get_or_init(|| {
        ExactEndgameConfig {
            max_cards: std::env::var("SHENGJI_EXACT_ENDGAME_CARDS")
                .ok()
                .and_then(|value| value.parse::<usize>().ok())
                .unwrap_or(0),
            max_nodes: std::env::var("SHENGJI_EXACT_ENDGAME_NODES")
                .ok()
                .and_then(|value| value.parse::<usize>().ok())
                .unwrap_or(50_000),
        }
        .bounded()
    })
}

fn normalized_entropy(scores: &[f64]) -> f64 {
    if scores.len() < 2 {
        return 0.0;
    }
    let probabilities = softmax(scores);
    let entropy = probabilities
        .into_iter()
        .filter(|probability| *probability > 0.0 && probability.is_finite())
        .map(|probability| -probability * probability.ln())
        .sum::<f64>();
    (entropy / (scores.len() as f64).ln()).clamp(0.0, 1.0)
}

fn adaptive_fraction_from_signals(
    min_fraction: f64,
    uncertainty: f64,
    pot_importance: f64,
    threshold_proximity: f64,
    late_hand: f64,
) -> f64 {
    let importance = (0.40 * uncertainty.clamp(0.0, 1.0)
        + 0.25 * pot_importance.clamp(0.0, 1.0)
        + 0.20 * threshold_proximity.clamp(0.0, 1.0)
        + 0.15 * late_hand.clamp(0.0, 1.0))
    .clamp(0.0, 1.0);
    min_fraction + (1.0 - min_fraction) * importance
}

fn adaptive_time_budget(
    play: &PlayPhase,
    candidates: &[ScoredPlay],
    hard_budget: Duration,
) -> Duration {
    let config = adaptive_budget_config();
    if !config.enabled || hard_budget.is_zero() {
        return hard_budget;
    }

    let uncertainty = normalized_entropy(
        &candidates
            .iter()
            .map(|candidate| candidate.score)
            .collect::<Vec<_>>(),
    );
    // Forty points on the table is already a major swing in ordinary Tractor;
    // larger throws simply saturate this importance signal.
    let pot_points = play
        .trick()
        .played_cards()
        .iter()
        .flat_map(|played| played.cards.iter())
        .filter_map(|card| card.points())
        .sum::<usize>();
    let pot_importance = (pot_points as f64 / 40.0).clamp(0.0, 1.0);

    let threshold_proximity = play
        .bot_step_size()
        .filter(|step| *step > 0)
        .map(|step| {
            let (points, _) = play.calculate_points();
            let remainder = points.rem_euclid(step) as f64;
            (remainder / step as f64).clamp(0.0, 1.0)
        })
        .unwrap_or(0.0);

    // This uses only public hand sizes (redacted hands preserve multiplicity).
    let players = play.propagated().players().len().max(1);
    let (_, removed) = play.piles_for_determinization();
    let initial_per_player = play
        .configured_cards_for_determinization()
        .map(|cards| {
            cards
                .len()
                .saturating_sub(play.kitty_size())
                .saturating_sub(removed.len())
                / players
        })
        .filter(|initial| *initial > 0);
    let late_hand = initial_per_player
        .and_then(|initial| {
            play.hands()
                .get(play.trick().next_player().unwrap_or(play.landlord()))
                .ok()
                .map(|hand| {
                    let remaining = hand.values().copied().sum::<usize>();
                    (1.0 - remaining.min(initial) as f64 / initial as f64).clamp(0.0, 1.0)
                })
        })
        // Old serialized rooms can lack enough deck configuration to infer a
        // denominator safely. Omitting this optional signal is conservative.
        .unwrap_or(0.0);

    let fraction = adaptive_fraction_from_signals(
        config.min_fraction,
        uncertainty,
        pot_importance,
        threshold_proximity,
        late_hand,
    );
    hard_budget.mul_f64(fraction.clamp(config.min_fraction, 1.0))
}

fn risk_adjusted_value(samples: &[f64], config: RiskConfig) -> f64 {
    if samples.is_empty() {
        return f64::NEG_INFINITY;
    }
    let mean = samples.iter().sum::<f64>() / samples.len() as f64;
    if !config.enabled() {
        return mean;
    }
    let variance = samples
        .iter()
        .map(|value| {
            let delta = value - mean;
            delta * delta
        })
        .sum::<f64>()
        / samples.len() as f64;
    let mut lower_tail = samples.to_vec();
    lower_tail.sort_by(f64::total_cmp);
    let tail_count =
        ((config.cvar_alpha * samples.len() as f64).ceil() as usize).clamp(1, samples.len());
    let cvar = lower_tail[..tail_count].iter().sum::<f64>() / tail_count as f64;
    (1.0 - config.cvar_weight) * mean + config.cvar_weight * cvar
        - config.stddev_penalty * variance.sqrt()
}

fn minmax_normalize(values: &[f64]) -> Option<Vec<f64>> {
    if values.is_empty() || values.iter().any(|value| !value.is_finite()) {
        return None;
    }
    let low = values.iter().copied().fold(f64::INFINITY, f64::min);
    let high = values.iter().copied().fold(f64::NEG_INFINITY, f64::max);
    let span = high - low;
    (span > 1e-6 && span.is_finite())
        .then(|| values.iter().map(|value| (value - low) / span).collect())
}

fn normalize_level_q(values: &[f64]) -> Option<Vec<f64>> {
    static MIN_SPAN: OnceLock<f64> = OnceLock::new();
    let min_span = *MIN_SPAN.get_or_init(|| {
        std::env::var("SHENGJI_Q_MIN_SPAN")
            .ok()
            .and_then(|value| value.parse::<f64>().ok())
            .filter(|value| value.is_finite() && *value >= 0.0)
            .unwrap_or(0.05)
    });
    if values.is_empty() || values.iter().any(|value| !value.is_finite()) {
        return None;
    }
    let low = values.iter().copied().fold(f64::INFINITY, f64::min);
    let high = values.iter().copied().fold(f64::NEG_INFINITY, f64::max);
    let span = high - low;
    (span >= min_span && span > 1e-6)
        .then(|| values.iter().map(|value| (value - low) / span).collect())
}

fn root_level_q(p: &PlayPhase, me: PlayerID, candidates: &[ScoredPlay]) -> Option<Vec<f64>> {
    let cards: Vec<Vec<Card>> = candidates
        .iter()
        .map(|candidate| candidate.cards.clone())
        .collect();
    let values = expert::action_q_candidates_net(p, me, &cards)?;
    (values.len() == candidates.len())
        .then(|| values.into_iter().map(f64::from).collect::<Vec<_>>())
}

fn argmax_earliest(values: &[f64]) -> usize {
    let mut best_index = 0;
    let mut best_value = f64::NEG_INFINITY;
    for (index, value) in values.iter().copied().enumerate() {
        if value > best_value {
            best_value = value;
            best_index = index;
        }
    }
    best_index
}

/// Run the determinized search and return the chosen cards, or `None` if no
/// candidate could be produced (caller should fall back to the heuristic /
/// dumb policy).
pub fn search_play(p: &PlayPhase, me: PlayerID, mut config: SearchConfig) -> Option<Vec<Card>> {
    let decision_start = Instant::now();
    // Candidate generation + policy pruning: rank by the configured policy (net
    // prior for Expert, playbook/heuristic for Enoch) and take the top-K.
    let mut candidates: Vec<ScoredPlay> = ranked_candidates(p, me, config.policy);
    if candidates.is_empty() {
        return None;
    }
    candidates.truncate(config.max_candidates.max(1));

    // If there's only one candidate, no need to search.
    if candidates.len() == 1 {
        return Some(candidates.remove(0).cards);
    }
    // Cache the typed Q values once for final blending / PUCT. Candidate ranking
    // may already have consulted Q while assembling top-K, but serving should not
    // run another uncharged inference after the timed search.
    let root_q_values = (config.policy == Policy::Net)
        .then(|| root_level_q(p, me, &candidates))
        .flatten();

    // Candidate construction/ranking is part of decision latency too. Adaptive
    // allocation may shorten routine decisions, but the caller's configured
    // budget remains a hard upper bound from `decision_start`.
    let target_budget = adaptive_time_budget(p, &candidates, config.time_budget);
    let decision_deadline = decision_start + target_budget;
    config.time_budget = decision_deadline.saturating_duration_since(Instant::now());
    if config.time_budget.is_zero() {
        return Some(candidates[0].cards.clone());
    }

    let mut rng = StdRng::seed_from_u64(config.seed);

    // PUCT mode (opt-in via SHENGJI_SEARCH_PUCT): allocate simulations to the
    // candidates by a PUCT/UCB rule — concentrating the budget on the 1–3
    // CONTESTED candidates — instead of the flat "every candidate, every world"
    // averaging below. Default OFF, so the entire flat path that follows is
    // byte-unchanged in production. See `docs/bot-training-roadmap.md` (pays off
    // most once the leaf is a learned value net, not the crude static eval).
    if puct_enabled() {
        return puct_search(
            p,
            me,
            &candidates,
            root_q_values.as_deref(),
            &config,
            &mut rng,
            decision_deadline,
        );
    }

    let mut totals = vec![0.0f64; candidates.len()];
    let mut counts = vec![0u32; candidates.len()];
    let risk = risk_config();
    let mut samples = risk
        .enabled()
        .then(|| vec![Vec::<f64>::new(); candidates.len()]);

    let start = Instant::now();
    let mut worlds_attempted = 0usize;
    let mut paired_worlds_done = 0usize;

    while worlds_attempted < config.max_worlds {
        if Instant::now() >= decision_deadline {
            break;
        }
        worlds_attempted += 1;

        // Full public memory is part of every honest observation and is therefore
        // independent of the root policy. Reuse one world and one rollout-random
        // stream across all candidates (common random numbers) for a paired,
        // lower-variance comparison.
        let world = match sample_world(p, me, &mut rng) {
            Some(w) => w,
            None => continue,
        };

        let rollout_seed = rng.gen::<u64>();
        let Some(values) = evaluate_paired_candidates(
            &world.play,
            me,
            &candidates,
            config.rollout_tricks,
            config.rollout_policy,
            rollout_seed,
            Some(decision_deadline),
        ) else {
            continue;
        };
        // Commit a world only after every candidate completed. We deliberately do
        // not stop halfway through a round: a timer expiring mid-round used to
        // give early candidates more samples and make strength depend on order.
        for (idx, value) in values.into_iter().enumerate() {
            totals[idx] += value;
            counts[idx] += 1;
            if let Some(samples) = &mut samples {
                samples[idx].push(value);
            }
        }
        paired_worlds_done += 1;
    }

    if search_trace_enabled() {
        let elapsed = start.elapsed();
        let time_bound = Instant::now() >= decision_deadline;
        eprintln!(
            "[search] seat={} cands={} paired_worlds={} attempts={}/{} elapsed={:.1}ms budget={}ms bound={}",
            me.0,
            candidates.len(),
            paired_worlds_done,
            worlds_attempted,
            config.max_worlds,
            elapsed.as_secs_f64() * 1000.0,
            config.time_budget.as_millis(),
            if time_bound { "TIME" } else { "WORLDS" },
        );
    }

    // A zero-sample search falls back to the policy prior as a whole. Never mix
    // heuristic-prior units with rollout-point units in one argmax.
    if paired_worlds_done == 0 {
        return Some(candidates[0].cards.clone());
    }
    debug_assert!(counts.windows(2).all(|pair| pair[0] == pair[1]));
    let avgs: Vec<f64> = totals
        .iter()
        .zip(&counts)
        .map(|(&total, &count)| total / count as f64)
        .collect();
    let estimates = if let Some(samples) = &samples {
        samples
            .iter()
            .map(|candidate_samples| risk_adjusted_value(candidate_samples, risk))
            .collect::<Vec<_>>()
    } else {
        // Preserve the established summation path exactly at neutral defaults.
        avgs.clone()
    };

    // Pick the best candidate. Candidates are heuristic-sorted, so the earliest
    // index wins ties.
    let best_idx = if config.policy == Policy::EnochHeuristic {
        // Enoch: the static leaf evaluator ([`evaluate_position`]) is playbook-
        // BLIND (points + generic control only), so on its own the search can
        // silently override the Enoch playbook among near-equal candidates — e.g.
        // pick a play the playbook heavily penalized once it survives into the
        // top-K (late game / few legal options). Blend a small amount of the
        // (min-max normalized) Enoch heuristic prior back into the FINAL selection
        // so the playbook breaks near-ties toward its move while a clearly-better
        // search value still wins. `candidates[i].score` is the playbook prior.
        const LAMBDA: f64 = 0.2;
        let norm = |xs: &[f64]| -> Vec<f64> {
            let lo = xs.iter().copied().fold(f64::INFINITY, f64::min);
            let hi = xs.iter().copied().fold(f64::NEG_INFINITY, f64::max);
            let span = hi - lo;
            if !span.is_finite() || span <= 0.0 {
                vec![0.0; xs.len()]
            } else {
                xs.iter().map(|&x| (x - lo) / span).collect()
            }
        };
        let norm_avg = norm(&estimates);
        let norm_heur = norm(&candidates.iter().map(|c| c.score).collect::<Vec<_>>());
        let mut bi = 0;
        let mut best = f64::NEG_INFINITY;
        for idx in 0..candidates.len() {
            let combined = norm_avg[idx] + LAMBDA * norm_heur[idx];
            if combined > best {
                best = combined;
                bi = idx;
            }
        }
        bi
    } else if config.policy == Policy::Net {
        let search_norm = minmax_normalize(&estimates);
        let q_norm = root_q_values.as_deref().and_then(normalize_level_q);
        match (search_norm, q_norm) {
            (Some(search_norm), Some(q_norm)) => {
                let weight = q_blend_weight();
                let combined: Vec<f64> = (0..candidates.len())
                    .map(|idx| (1.0 - weight) * search_norm[idx] + weight * q_norm[idx])
                    .collect();
                argmax_earliest(&combined)
            }
            (None, Some(q_norm)) => argmax_earliest(&q_norm),
            _ => argmax_earliest(&estimates),
        }
    } else {
        let mut bi = 0;
        let mut best = f64::NEG_INFINITY;
        for (idx, &avg) in estimates.iter().enumerate() {
            if avg > best {
                best = avg;
                bi = idx;
            }
        }
        bi
    };

    Some(candidates[best_idx].cards.clone())
}

/// Evaluate a complete candidate round against one world with common random
/// numbers. A round is all-or-nothing so callers never compare means based on
/// different world sets merely because the wall clock expired between candidates.
fn evaluate_paired_candidates(
    world: &PlayPhase,
    me: PlayerID,
    candidates: &[ScoredPlay],
    rollout_tricks: usize,
    rollout_policy: Policy,
    rollout_seed: u64,
    deadline: Option<Instant>,
) -> Option<Vec<f64>> {
    let mut values = Vec::with_capacity(candidates.len());
    for candidate in candidates {
        // Re-seeding every candidate gives each hypothetical action the same
        // rollout-random stream. The paths may consume it differently after they
        // diverge, but candidate iteration order cannot change its random draws.
        let mut candidate_rng = StdRng::seed_from_u64(rollout_seed);
        values.push(evaluate_candidate(
            world,
            me,
            &candidate.cards,
            rollout_tricks,
            rollout_policy,
            &mut candidate_rng,
            deadline,
        )?);
    }
    Some(values)
}

/// PUCT/UCB simulation allocation over the (already policy-pruned) candidate set,
/// as an opt-in alternative to [`search_play`]'s flat per-world averaging.
///
/// Each simulation ("pull") selects the candidate maximizing
/// `Q̂(i) + C·P(i)·√ΣN / (1 + N_i)`, samples a FRESH determinized world, rolls the
/// candidate out, and updates that candidate's value/visit counts — concentrating
/// the budget on the 1–3 contested candidates instead of spreading it evenly. `Q̂`
/// is the per-candidate mean leaf value MIN-MAX normalized to `[0,1]` so the
/// exploration term is on a comparable, scale-free footing; `P` is uniform over
/// the top-K (the policy already pruned to the top-K, so within them we let UCB
/// allocate). The recommended move is the MOST-VISITED candidate (the robust
/// AlphaZero choice), tie-broken by mean value then heuristic order.
///
/// Trade-off (see the roadmap): this samples a fresh world per pull, giving up the
/// flat path's paired-world variance reduction in exchange for selective depth —
/// a win mainly once the leaf evaluator is a real value net rather than the crude
/// static eval. Progressive widening (searching beyond the top-K) is a future
/// extension; this version keeps the same candidate set as the flat path so an
/// A/B isolates the allocation change.
fn puct_search(
    p: &PlayPhase,
    me: PlayerID,
    candidates: &[ScoredPlay],
    root_q: Option<&[f64]>,
    config: &SearchConfig,
    rng: &mut StdRng,
    deadline: Instant,
) -> Option<Vec<Card>> {
    const C_PUCT: f64 = 1.5;
    let n = candidates.len();
    let uniform = vec![1.0 / n as f64; n];
    let prior = root_q
        .and_then(|values| {
            let normalized = normalize_level_q(values)?;
            // A modest temperature keeps a sparse/noisy pilot head from
            // starving alternatives while still directing visits toward its
            // calibrated action-value preference.
            Some(softmax(
                &normalized
                    .into_iter()
                    .map(|value| value * 2.0)
                    .collect::<Vec<_>>(),
            ))
        })
        .filter(|values| values.len() == n)
        .unwrap_or(uniform);
    let mut q_sum = vec![0.0f64; n];
    let mut counts = vec![0u32; n];
    let risk = risk_config();
    let mut samples = risk.enabled().then(|| vec![Vec::<f64>::new(); n]);

    // Match the flat path's rollout budget: it does `max_worlds` worlds × `n`
    // candidate rollouts; here each pull is one rollout, so allow `max_worlds·n`.
    let pulls = config.max_worlds.saturating_mul(n);
    let start = Instant::now();

    // Mandatory paired warm-up: when there is enough budget to begin one world,
    // every candidate gets the same world and random stream before UCB may focus
    // on a subset. This removes the old zero-as-Q bias and guarantees at least one
    // comparable sample per candidate when any simulation is possible.
    if pulls >= n && Instant::now() < deadline {
        if let Some(world) = sample_world(p, me, rng) {
            let rollout_seed = rng.gen::<u64>();
            if let Some(values) = evaluate_paired_candidates(
                &world.play,
                me,
                candidates,
                config.rollout_tricks,
                config.rollout_policy,
                rollout_seed,
                Some(deadline),
            ) {
                for (idx, value) in values.into_iter().enumerate() {
                    q_sum[idx] += value;
                    counts[idx] += 1;
                    if let Some(samples) = &mut samples {
                        samples[idx].push(value);
                    }
                }
            }
        }
    }

    // Selective allocation is meaningful only after the common baseline exists.
    // If the world/candidate set could not complete that baseline, use the prior
    // rather than manufacturing an order-dependent partially visited search.
    if counts.iter().all(|&count| count == 0) {
        return Some(candidates[0].cards.clone());
    }

    for _ in n..pulls {
        if Instant::now() >= deadline {
            break;
        }
        // Min-max normalize the current per-candidate mean values to [0,1] so the
        // exploitation term is comparable to the (scale-free) exploration term.
        let means: Vec<f64> = (0..n)
            .map(|i| {
                if counts[i] > 0 {
                    if risk.enabled() {
                        risk_adjusted_value(
                            &samples.as_ref().expect("risk samples enabled")[i],
                            risk,
                        )
                    } else {
                        q_sum[i] / counts[i] as f64
                    }
                } else {
                    0.0
                }
            })
            .collect();
        let lo = means.iter().copied().fold(f64::INFINITY, f64::min);
        let hi = means.iter().copied().fold(f64::NEG_INFINITY, f64::max);
        let span = (hi - lo).max(1e-9);
        let total: u32 = counts.iter().sum();
        let sqrt_total = (total as f64).sqrt();

        let mut best_i = 0;
        let mut best_u = f64::NEG_INFINITY;
        for i in 0..n {
            let q_norm = (means[i] - lo) / span;
            let u = q_norm + C_PUCT * prior[i] * sqrt_total / (1.0 + counts[i] as f64);
            if u > best_u {
                best_u = u;
                best_i = i;
            }
        }

        let world = match sample_world(p, me, rng) {
            Some(w) => w,
            None => continue,
        };
        if let Some(v) = evaluate_candidate(
            &world.play,
            me,
            &candidates[best_i].cards,
            config.rollout_tricks,
            config.rollout_policy,
            rng,
            Some(deadline),
        ) {
            q_sum[best_i] += v;
            counts[best_i] += 1;
            if let Some(samples) = &mut samples {
                samples[best_i].push(v);
            }
        }
    }

    if search_trace_enabled() {
        eprintln!(
            "[search/puct] seat={} cands={} pulls={:?} visits={:?} elapsed={:.1}ms",
            me.0,
            n,
            counts.iter().sum::<u32>(),
            counts,
            start.elapsed().as_secs_f64() * 1000.0,
        );
    }

    // Recommend the MOST-VISITED candidate (AlphaZero's robust choice); tie-break
    // by higher mean value, then earlier (higher heuristic) index. A candidate
    // never sampled (no world satisfied it) keeps -inf mean so it loses ties.
    let mut best_i = 0;
    let mut best_key = (0u32, f64::NEG_INFINITY);
    for i in 0..n {
        let mean = if counts[i] > 0 {
            if risk.enabled() {
                risk_adjusted_value(&samples.as_ref().expect("risk samples enabled")[i], risk)
            } else {
                q_sum[i] / counts[i] as f64
            }
        } else {
            f64::NEG_INFINITY
        };
        let key = (counts[i], mean);
        if key.0 > best_key.0 || (key.0 == best_key.0 && key.1 > best_key.1) {
            best_key = key;
            best_i = i;
        }
    }
    Some(candidates[best_i].cards.clone())
}

/// Run a PERFECT-INFORMATION search and return the chosen cards, or `None` if no
/// candidate could be produced (caller should fall back to the heuristic / dumb
/// policy).
///
/// # Perfect information (Omniscient cheater tier ONLY)
///
/// Unlike [`search_play`], this does NOT sample hidden hands. The play phase `p`
/// passed in is the TRUE world — every seat's real cards — because it was
/// obtained for an `Omniscient` bot via the centralized honesty bypass
/// ([`crate::bot::observed_state`]). We therefore evaluate every candidate
/// against that single known world using full (un-truncated) rollouts, with no
/// ε-noise and no softmax temperature (greedy on the search value). This reuses
/// exactly the same machinery ([`evaluate_candidate`] → [`rollout`] →
/// [`evaluate_position`]) as the honest determinized search; only the world source
/// differs (one true world vs. many sampled worlds).
///
/// This is the only search entry point that reads the real opponents' hands, and
/// it is reachable solely through the `Omniscient` dispatch in
/// [`crate::bot::policy`].
pub fn search_play_perfect_info(
    p: &PlayPhase,
    me: PlayerID,
    mut config: SearchConfig,
) -> Option<Vec<Card>> {
    let decision_start = Instant::now();
    let mut candidates: Vec<ScoredPlay> = ranked_candidates(p, me, config.policy);
    if candidates.is_empty() {
        return None;
    }
    candidates.truncate(config.max_candidates.max(1));
    if candidates.len() == 1 {
        return Some(candidates.remove(0).cards);
    }

    let target_budget = adaptive_time_budget(p, &candidates, config.time_budget);
    let root_deadline = decision_start + target_budget;
    let exact = exact_endgame_config();
    if exact.enabled() {
        if let Some(result) = endgame::solve_root_with_deadline(p, me, exact, Some(root_deadline)) {
            if search_trace_enabled() {
                eprintln!(
                    "[search/exact] seat={} cards={} nodes={} elapsed={:.1}ms value={:.3}",
                    me.0,
                    exact.max_cards,
                    result.nodes,
                    decision_start.elapsed().as_secs_f64() * 1000.0,
                    result.value,
                );
            }
            return Some(result.cards);
        }
    }

    // An unsuccessful exact attempt is charged to the same absolute deadline;
    // it never grants the fallback search a fresh budget.
    config.time_budget = root_deadline.saturating_duration_since(Instant::now());
    if config.time_budget.is_zero() {
        return Some(candidates[0].cards.clone());
    }

    let mut rng = StdRng::seed_from_u64(config.seed);

    // Evaluate complete rounds against the SINGLE true world `p`. Every candidate
    // in a round gets the same rollout-random stream, and only a fully completed
    // round is committed, so wall-clock expiry cannot privilege candidates
    // earlier in the ranking.
    let mut totals = vec![0.0f64; candidates.len()];
    let risk = risk_config();
    let mut samples = risk
        .enabled()
        .then(|| vec![Vec::<f64>::new(); candidates.len()]);
    let mut rounds = 0u32;
    for _ in 0..config.max_worlds {
        if Instant::now() >= root_deadline {
            break;
        }
        let rollout_seed = rng.gen::<u64>();
        let Some(values) = evaluate_paired_candidates(
            p,
            me,
            &candidates,
            config.rollout_tricks,
            config.rollout_policy,
            rollout_seed,
            Some(root_deadline),
        ) else {
            continue;
        };
        for (idx, value) in values.into_iter().enumerate() {
            totals[idx] += value;
            if let Some(samples) = &mut samples {
                samples[idx].push(value);
            }
        }
        rounds += 1;
    }

    if rounds == 0 {
        return Some(candidates[0].cards.clone());
    }
    let mut best_idx = 0usize;
    let mut best_avg = f64::NEG_INFINITY;
    for (idx, total) in totals.into_iter().enumerate() {
        let avg = if risk.enabled() {
            risk_adjusted_value(&samples.as_ref().expect("risk samples enabled")[idx], risk)
        } else {
            total / rounds as f64
        };
        if avg > best_avg {
            best_avg = avg;
            best_idx = idx;
        }
    }

    Some(candidates[best_idx].cards.clone())
}

/// Rank the legal candidates for `me` under the given [`Policy`] (best first).
///
/// For [`Policy::Heuristic`] this is exactly the heuristic ranking. For
/// [`Policy::Net`] we generate the same legal candidate set and order it by a
/// BLEND of the learned net's per-candidate distribution and the heuristic's
/// (the learned policy prior, regularized by the hand heuristic — see the inline
/// comment). If the net can't run (model missing/failed, or fewer than two
/// candidates), we transparently fall back to the heuristic ranking, so the
/// search is never starved of candidates.
fn ranked_candidates(p: &PlayPhase, me: PlayerID, policy: Policy) -> Vec<ScoredPlay> {
    canonicalize_ranked_candidates(ranked_candidates_raw(p, me, policy))
}

fn canonicalize_ranked_candidates(candidates: Vec<ScoredPlay>) -> Vec<ScoredPlay> {
    let mut keyed = candidates
        .into_iter()
        .map(|candidate| {
            let mut key = candidate
                .cards
                .iter()
                .map(|card| card.as_char())
                .collect::<Vec<_>>();
            key.sort_unstable();
            (candidate, key)
        })
        .collect::<Vec<_>>();

    // Preserve policy score as the primary ranking, but make every tie independent
    // of HashMap iteration order. Equivalent multisets are one physical action and
    // are deduplicated after sorting.
    keyed.sort_by(|(a, a_key), (b, b_key)| {
        let a_score = if a.score.is_finite() {
            a.score
        } else {
            f64::NEG_INFINITY
        };
        let b_score = if b.score.is_finite() {
            b.score
        } else {
            f64::NEG_INFINITY
        };
        b_score.total_cmp(&a_score).then_with(|| a_key.cmp(b_key))
    });
    let mut seen = HashSet::new();
    keyed
        .into_iter()
        .filter_map(|(candidate, key)| seen.insert(key).then_some(candidate))
        .collect()
}

fn ranked_candidates_raw(p: &PlayPhase, me: PlayerID, policy: Policy) -> Vec<ScoredPlay> {
    let leading = p.trick().played_cards().is_empty();

    let heuristic_ranked = || -> Vec<ScoredPlay> {
        if leading {
            heuristics::ranked_leads(p, me)
        } else {
            heuristics::ranked_follows(p, me)
        }
    };

    match policy {
        Policy::Heuristic => heuristic_ranked(),
        Policy::EnochHeuristic => {
            if leading {
                heuristics::ranked_leads_enoch(p, me)
            } else {
                heuristics::ranked_follows_enoch(p, me)
            }
        }
        Policy::Net => {
            // Generate the legal candidates the net should rank.
            let cands: Vec<Vec<Card>> = if leading {
                heuristics::lead_candidates(p, me)
            } else {
                heuristics::follow_candidates(p, me)
            };
            if cands.len() < 2 {
                // 0 or 1 candidate: nothing for the net to discriminate; defer to
                // the heuristic ranking (which also handles its own fallbacks).
                return heuristic_ranked();
            }
            // A sparse schema-v2 Q head is an additional calibrated signal, not
            // a wholesale replacement for the established policy+heuristic prior.
            // Near-constant Q is ignored by `normalize_level_q`.
            let q_prior = expert::action_q_candidates_net(p, me, &cands)
                .filter(|values| values.len() == cands.len())
                .map(|values| values.into_iter().map(f64::from).collect::<Vec<_>>())
                .as_deref()
                .and_then(normalize_level_q)
                .map(|values| {
                    softmax(
                        &values
                            .into_iter()
                            .map(|value| value * 2.0)
                            .collect::<Vec<_>>(),
                    )
                });
            let net_scores = match expert::score_candidates_net(p, me, &cands) {
                Some(s) => s,
                // Net unavailable: fall back to the heuristic prior.
                None => return heuristic_ranked(),
            };
            // BLENDED prior: rank by a convex mix of the net's per-candidate
            // probability and the heuristic's, rather than the net alone. The
            // distilled net and the hand heuristic make *different* mistakes; each
            // is on its own ~as good a prior as the other, but mixing them yields a
            // strictly more informed candidate ordering — which is what lets the
            // net-guided Expert search edge out the heuristic-only search on
            // the same compute. Both signals are squashed to a comparable [0,1]
            // softmax distribution so neither's raw scale dominates.
            let ctx = heuristics::EvalCtx::build(p, me);
            let heur_scores: Vec<f64> = cands
                .iter()
                .map(|c| {
                    if leading {
                        heuristics::score_lead(&ctx, p, c)
                    } else {
                        heuristics::score_follow(&ctx, p, c)
                    }
                })
                .collect();
            let net_probs = softmax(&net_scores.iter().map(|&s| s as f64).collect::<Vec<_>>());
            let heur_probs = softmax(&heur_scores);
            // Weight: lean on the net (the distilled teacher signal) but keep a
            // meaningful heuristic contribution so its complementary strengths
            // (e.g. crisp end-game / trump-conservation rules) survive.
            const NET_W: f64 = 0.6;
            const HEUR_W: f64 = 0.4;
            let mut scored: Vec<ScoredPlay> = cands
                .into_iter()
                .enumerate()
                .map(|(i, cards)| ScoredPlay {
                    cards,
                    score: {
                        let base = NET_W * net_probs[i] + HEUR_W * heur_probs[i];
                        q_prior
                            .as_ref()
                            .map(|q| (1.0 - q_blend_weight()) * base + q_blend_weight() * q[i])
                            .unwrap_or(base)
                    },
                })
                .collect();
            scored.sort_by(|a, b| {
                b.score
                    .partial_cmp(&a.score)
                    .unwrap_or(std::cmp::Ordering::Equal)
            });
            scored
        }
    }
}

/// Numerically-stable softmax over a slice of scores, returning a probability
/// distribution of the same length. An empty input yields an empty vector. Used
/// to put the net and heuristic candidate scores on the same [0,1] scale before
/// blending them into the search prior.
fn softmax(scores: &[f64]) -> Vec<f64> {
    if scores.is_empty() {
        return Vec::new();
    }
    let max = scores.iter().copied().fold(f64::NEG_INFINITY, f64::max);
    if !max.is_finite() {
        // All -inf (e.g. empty candidates scored): uniform.
        let u = 1.0 / scores.len() as f64;
        return vec![u; scores.len()];
    }
    let exps: Vec<f64> = scores.iter().map(|&s| (s - max).exp()).collect();
    let sum: f64 = exps.iter().sum();
    if sum <= 0.0 || !sum.is_finite() {
        let u = 1.0 / scores.len() as f64;
        return vec![u; scores.len()];
    }
    exps.into_iter().map(|e| e / sum).collect()
}

/// Apply `cards` for `me` in a clone of `world`, then roll the rest of the
/// position out with `policy` and return the position value from `me`'s team's
/// perspective. Returns `None` if the candidate is somehow illegal in this world
/// (it should be legal, since it was generated from the redacted hand, which is
/// a subset of this world).
fn evaluate_candidate(
    world: &PlayPhase,
    me: PlayerID,
    cards: &[Card],
    rollout_tricks: usize,
    policy: Policy,
    rng: &mut StdRng,
    deadline: Option<Instant>,
) -> Option<f64> {
    // Gate at the common world root so every candidate in a paired comparison
    // uses the same value units. A large lead must not become "exact" merely
    // because it sheds enough cards to cross the threshold while a single-card
    // alternative falls through to a point-valued rollout leaf.
    let exact = exact_endgame_config();
    let use_exact = endgame::eligible_for_exact(world, exact);
    let mut sim = world.clone();
    // Play our candidate.
    if sim.play_cards(me, cards).is_err() {
        return None;
    }

    // In a fully materialized sampled world, replace the noisy rollout/static
    // leaf with strict minimax once the residual tree is tiny. Honest play never
    // invokes this on the real hidden hands. An over-budget solve invalidates the
    // candidate round instead of mixing a partial exact result with rollout units.
    if use_exact {
        match endgame::solve_value_if_eligible(&sim, me, exact, deadline) {
            ExactValueAttempt::Solved(value) => return Some(value),
            ExactValueAttempt::Aborted | ExactValueAttempt::Ineligible => return None,
        }
    }

    // Roll out a bounded number of tricks with `policy` as every seat's policy,
    // then statically evaluate. Deeper look-ahead (`rollout_tricks`) yields a
    // more accurate value at higher cost; the static evaluator credits the
    // trick-winning potential still in our hand so we don't have to play every
    // card to value the position.
    let players = sim.propagated().players().len();
    // `saturating_mul` so a `rollout_tricks` of `usize::MAX` (the Omniscient
    // "roll out the whole hand" sentinel) caps at `usize::MAX` plies instead of
    // overflowing; the rollout loop terminates anyway once the hand is finished.
    let max_plies = players.saturating_mul(rollout_tricks.max(1));
    if !rollout(&mut sim, max_plies, policy, rng, deadline) {
        return None;
    }

    Some(evaluate_position(&sim, me))
}

/// Choose the rollout move for `actor` under `policy`, returning the ranked
/// candidate list (best first) so the caller can fall back to lower-ranked plays
/// if the top pick is illegal in this determinized world.
///
/// For [`Policy::Net`] we order the legal candidates by the learned net (the
/// policy-guided rollout); if the net can't score this position we fall back to
/// the heuristic ranking. `Policy::Heuristic` always uses the heuristic ranking.
fn rollout_ranked(
    sim: &PlayPhase,
    actor: PlayerID,
    leading: bool,
    policy: Policy,
) -> Vec<Vec<Card>> {
    // Knowledge/feature construction is observer-aware even on a materialized
    // sampled world: it uses only `actor`'s hand identities, public history and
    // public pile sizes. We can therefore borrow the simulation directly without
    // deep-cloning/redacting its growing history on every rollout ply.
    let view = sim;
    let heuristic_cards = || -> Vec<Vec<Card>> {
        let ranked = if leading {
            heuristics::ranked_leads_for_rollout(view, actor)
        } else {
            heuristics::ranked_follows_for_rollout(view, actor)
        };
        ranked.into_iter().map(|s| s.cards).collect()
    };

    match policy {
        Policy::Heuristic => heuristic_cards(),
        Policy::EnochHeuristic => {
            let ranked = if leading {
                heuristics::ranked_leads_enoch_for_rollout(view, actor)
            } else {
                heuristics::ranked_follows_enoch_for_rollout(view, actor)
            };
            ranked.into_iter().map(|s| s.cards).collect()
        }
        Policy::Net => {
            let cands: Vec<Vec<Card>> = if leading {
                heuristics::rollout_lead_candidates(view, actor)
            } else {
                heuristics::rollout_follow_candidates(view, actor)
            };
            if cands.len() < 2 {
                return heuristic_cards();
            }
            match expert::score_candidates_net(view, actor, &cands) {
                Some(scores) => {
                    let mut idx: Vec<usize> = (0..cands.len()).collect();
                    idx.sort_by(|&a, &b| {
                        scores[b]
                            .partial_cmp(&scores[a])
                            .unwrap_or(std::cmp::Ordering::Equal)
                    });
                    idx.into_iter().map(|i| cands[i].clone()).collect()
                }
                None => heuristic_cards(),
            }
        }
    }
}

/// Greedily roll the play-phase forward using `policy` for whichever seat is to
/// act, finishing tricks as needed, for up to `max_plies` card plays. Mutates
/// `sim` in place.
fn rollout(
    sim: &mut PlayPhase,
    max_plies: usize,
    policy: Policy,
    rng: &mut StdRng,
    deadline: Option<Instant>,
) -> bool {
    use rand::seq::SliceRandom;

    let mut plies = 0;
    while plies < max_plies {
        if deadline.map(|end| Instant::now() >= end).unwrap_or(false) {
            return false;
        }
        if sim.game_finished() {
            break;
        }
        match sim.trick().next_player() {
            None => {
                // Trick complete: finish it (winner leads next).
                if sim.finish_trick().is_err() {
                    break;
                }
            }
            Some(actor) => {
                let leading = sim.trick().played_cards().is_empty();
                let mut ranked = rollout_ranked(sim, actor, leading, policy);
                if ranked.is_empty() {
                    break;
                }
                // Use the policy-best move, with a small amount of noise so
                // rollouts explore (paired worlds already share the deal).
                let pick = if ranked.len() > 1 && rng.gen_bool(0.15) {
                    // occasionally take the 2nd-best to add variance
                    ranked.remove(1)
                } else {
                    ranked.remove(0)
                };
                let mut cards = pick;
                // Defensive: if the chosen play is somehow illegal in this
                // determinized world, fall back to any legal candidate.
                if sim.play_cards(actor, &cards).is_err() {
                    // Try other candidates.
                    let alts = if leading {
                        heuristics::rollout_lead_candidates(sim, actor)
                    } else {
                        heuristics::rollout_follow_candidates(sim, actor)
                    };
                    let mut ok = false;
                    let mut alts = alts;
                    alts.shuffle(rng);
                    for alt in alts {
                        if sim.play_cards(actor, &alt).is_ok() {
                            cards = alt;
                            ok = true;
                            break;
                        }
                    }
                    if !ok {
                        break;
                    }
                }
                let _ = cards;
                plies += 1;
            }
        }
    }

    // If the cutoff landed exactly on the last follower, settle that completed
    // trick before the leaf evaluation. Otherwise its points (and, on the final
    // trick, the kitty multiplier) remain on the table and are omitted from
    // `calculate_points`, creating a seat/cutoff-dependent evaluation bias.
    if sim.trick().next_player().is_none() {
        let _ = sim.finish_trick();
    }
    true
}

/// Static evaluation of a play-phase position from `me`'s team's perspective.
///
/// Combines the realized point differential so far (the non-landlord point total
/// is what the scoring engine ultimately uses) with a positional term crediting
/// the *trick-winning potential* still in our hand. Because rollouts are
/// shallow, the positional term is what lets the search prefer plays that
/// preserve our ability to capture future point tricks rather than only chasing
/// immediate points.
fn evaluate_position(sim: &PlayPhase, me: PlayerID) -> f64 {
    use shengji_mechanics::types::{Card, EffectiveSuit, Number};

    let team = sim.landlords_team();
    let me_is_landlord_team = team.contains(&me);

    // `calculate_points` returns (non_landlord_points, observed). The defending
    // (landlord) team wants non_landlord_points LOW; the attacking team wants it
    // HIGH. We orient the score so HIGHER is always better for `me`'s team.
    let (non_landlord_points, _) = sim.calculate_points();
    let realized = if me_is_landlord_team {
        -(non_landlord_points as f64)
    } else {
        non_landlord_points as f64
    };

    // Positional control: high cards and trumps remaining in our own hand are
    // future trick winners. Value them so the search keeps control rather than
    // dumping winners prematurely.
    let trump = sim.trump();
    let control = sim
        .hands()
        .get(me)
        .map(|h| {
            let mut v = 0.0;
            for (card, &ct) in h.iter() {
                let c = *card;
                let is_trump = trump.effective_suit(c) == EffectiveSuit::Trump;
                let mut w = 0.0;
                match c {
                    Card::BigJoker | Card::SmallJoker => w = 1.6,
                    Card::Suited { number, .. } => {
                        if is_trump {
                            w = 0.8;
                        } else if number == Number::Ace {
                            w = 1.0;
                        } else if number == Number::King {
                            w = 0.5;
                        }
                    }
                    Card::Unknown => {}
                }
                v += w * ct as f64;
            }
            v
        })
        .unwrap_or(0.0);

    let static_eval = realized + control;

    // A schema-v2 state head predicts the real hand objective (win plus awarded
    // levels). Replace the point-valued leaf wholesale; never multiply it by the
    // legacy point normalizer or blend incompatible units. Finished simulations
    // use exact engine scoring, while an inference failure falls back to a bounded
    // static proxy so every candidate remains comparable in roughly [-1, 1].
    if level_value_leaf_enabled() {
        if sim.game_finished() {
            if let Some(value) = terminal_level_utility(sim, me) {
                return value;
            }
        } else if let Some(value) = level_value_estimate(sim, me) {
            return value;
        }
        return (static_eval / expert::VALUE_NORM).tanh();
    }

    // Optional learned-VALUE blend. Default OFF (`SHENGJI_VALUE_WEIGHT` unset → 0),
    // so this is EXACTLY the static eval above and production behavior is
    // byte-unchanged until a value-head model is trained AND the knob is set. When
    // on (and a 2-output value model is loaded), blend the net's terminal-margin
    // estimate — a far better leaf signal than the shallow-rollout static eval.
    let w = value_weight();
    if w <= 0.0 {
        return static_eval;
    }
    match net_value_estimate(sim, me) {
        Some(v) => (1.0 - w) * static_eval + w * v,
        // Policy-only / legacy model, finished leaf, or no clean to-act seat:
        // fall back to the static eval so the search never stalls or misbehaves.
        None => static_eval,
    }
}

fn terminal_level_utility(sim: &PlayPhase, me: PlayerID) -> Option<f64> {
    let score = sim.current_game_score().ok()?;
    let me_is_landlord = sim.landlords_team().contains(&me);
    let me_won = me_is_landlord == score.landlord_won;
    let levels = if score.landlord_won {
        score.landlord_delta
    } else {
        score.non_landlord_delta
    };
    let magnitude = ((1 + levels) as f64 / expert::LEVEL_UTILITY_NORM as f64).min(1.0);
    Some(if me_won { magnitude } else { -magnitude })
}

/// Typed schema-v2 state value, oriented from the next actor to the root team.
/// The state head masks every action-dependent feature, so one legal probe
/// candidate is sufficient and avoids repeating identical V inference rows.
fn level_value_estimate(sim: &PlayPhase, me: PlayerID) -> Option<f64> {
    let actor = sim.trick().next_player()?;
    let leading = sim.trick().played_cards().is_empty();
    let probe = if leading {
        heuristics::rollout_lead_candidates(sim, actor)
    } else {
        heuristics::rollout_follow_candidates(sim, actor)
    }
    .into_iter()
    .next()?;
    let value = expert::level_value_candidates_net(sim, actor, &[probe])?
        .into_iter()
        .next()? as f64;
    if !value.is_finite() {
        return None;
    }
    let actor_on_my_team =
        sim.landlords_team().contains(&actor) == sim.landlords_team().contains(&me);
    Some(if actor_on_my_team { value } else { -value })
}

/// The learned VALUE-head estimate of leaf position `sim`, oriented for `me`'s
/// team and scaled back to POINTS (so it blends with the static eval's point
/// units), or `None` when there is nothing meaningful to predict: the game is
/// already finished (the static `realized` is then exact), there is no clean seat
/// to act, the to-act seat has no legal candidates, or the loaded model has no
/// value head (policy-only / legacy → the blend stays disabled).
///
/// The value head was trained as "normalized terminal margin oriented for the
/// ACTING seat's team", so we score the to-act seat's candidates, take the best
/// (the seat plays to maximize its OWN team), then orient to `me`'s team. Reads
/// only `sim` (a sampled determinized world during search, exactly like the
/// rollout policy), so it never touches the real hidden hands.
fn net_value_estimate(sim: &PlayPhase, me: PlayerID) -> Option<f64> {
    if sim.game_finished() {
        return None;
    }
    let actor = sim.trick().next_player()?;
    let leading = sim.trick().played_cards().is_empty();
    let cands = if leading {
        heuristics::rollout_lead_candidates(sim, actor)
    } else {
        heuristics::rollout_follow_candidates(sim, actor)
    };
    if cands.is_empty() {
        return None;
    }
    // Typed API accepts only a legacy `normalized_point_margin` head. A schema-v2
    // level-utility V is intentionally rejected rather than multiplied by the
    // legacy point scale and blended into an incompatible static leaf.
    let values = expert::point_value_candidates_net(sim, actor, &cands)?;
    let best = values.iter().copied().fold(f32::NEG_INFINITY, f32::max) as f64;
    if !best.is_finite() {
        return None;
    }
    // `best` is oriented for the acting seat's team; orient to `me`'s team.
    let team = sim.landlords_team();
    let actor_on_my_team = team.contains(&me) == team.contains(&actor);
    let v_for_me = if actor_on_my_team { best } else { -best };
    Some(v_for_me * expert::VALUE_NORM)
}

#[cfg(test)]
mod tests {
    use super::{
        adaptive_fraction_from_signals, canonicalize_ranked_candidates, normalized_entropy,
        risk_adjusted_value, RiskConfig, ScoredPlay,
    };
    use shengji_mechanics::types::{Card, Number, Suit};

    fn card(suit: Suit, number: Number) -> Card {
        Card::Suited { suit, number }
    }

    fn keys(candidates: &[ScoredPlay]) -> Vec<Vec<char>> {
        candidates
            .iter()
            .map(|candidate| {
                let mut key = candidate
                    .cards
                    .iter()
                    .map(|card| card.as_char())
                    .collect::<Vec<_>>();
                key.sort_unstable();
                key
            })
            .collect()
    }

    #[test]
    fn root_candidate_order_is_canonical_and_deduplicated() {
        let club_three = card(Suit::Clubs, Number::Three);
        let heart_four = card(Suit::Hearts, Number::Four);
        let spade_five = card(Suit::Spades, Number::Five);
        let input = vec![
            ScoredPlay {
                cards: vec![heart_four],
                score: 1.0,
            },
            ScoredPlay {
                cards: vec![club_three],
                score: 1.0,
            },
            // Same physical multiset in another order and at a lower score.
            ScoredPlay {
                cards: vec![spade_five, club_three],
                score: 0.5,
            },
            ScoredPlay {
                cards: vec![club_three, spade_five],
                score: 0.25,
            },
        ];

        let mut reversed = input.clone();
        reversed.reverse();
        let first = canonicalize_ranked_candidates(input);
        let second = canonicalize_ranked_candidates(reversed);
        assert_eq!(keys(&first), keys(&second));
        assert_eq!(first.len(), 3, "equivalent card multisets are one action");
        assert!(first[0].score >= first[1].score);
        assert!(first[1].score >= first[2].score);
    }

    #[test]
    fn adaptive_fraction_is_bounded_and_monotone_in_importance() {
        let minimum = 0.35;
        let routine = adaptive_fraction_from_signals(minimum, 0.0, 0.0, 0.0, 0.0);
        let uncertain = adaptive_fraction_from_signals(minimum, 1.0, 0.0, 0.0, 0.0);
        let critical = adaptive_fraction_from_signals(minimum, 1.0, 1.0, 1.0, 1.0);
        assert_eq!(routine, minimum);
        assert!(uncertain > routine);
        assert!((critical - 1.0).abs() < f64::EPSILON);
        assert!(routine >= minimum && critical <= 1.0);
    }

    #[test]
    fn candidate_entropy_identifies_contested_choices() {
        let contested = normalized_entropy(&[0.0, 0.0, 0.0]);
        let obvious = normalized_entropy(&[20.0, 0.0, 0.0]);
        assert!((contested - 1.0).abs() < 1e-12);
        assert!(obvious < 0.01);
    }

    #[test]
    fn risk_defaults_to_mean_and_penalizes_lower_tail_variance() {
        let neutral = RiskConfig {
            stddev_penalty: 0.0,
            cvar_weight: 0.0,
            cvar_alpha: 0.25,
        };
        assert_eq!(risk_adjusted_value(&[-2.0, 2.0], neutral), 0.0);

        let cautious = RiskConfig {
            stddev_penalty: 0.25,
            cvar_weight: 0.5,
            cvar_alpha: 0.5,
        };
        assert!(
            risk_adjusted_value(&[-2.0, 2.0], cautious)
                < risk_adjusted_value(&[0.0, 0.0], cautious)
        );
    }
}
