//! Determinized Monte-Carlo search for the Hard difficulty tier.
//!
//! This is a wall-clock-capped, single-observer determinized search over the
//! trick phase. For the acting player's candidate moves (generated by the
//! engine's legal-move generators and pruned by the heuristic), we:
//!
//! 1. Sample N plausible worlds (full hands for every seat) consistent with the
//!    redacted view — see [`crate::bot::determinize`]. We NEVER look at the real
//!    hidden hands; determinization is the only window into them.
//! 2. In each world, apply the candidate move on a *cloned* engine play-phase,
//!    then play the trick out (and a short greedy continuation) using the
//!    heuristic as the rollout policy for every seat.
//! 3. Score the resulting position from the acting player's team's perspective
//!    (points captured + a positional bonus) and average over worlds.
//!
//! We then pick the candidate with the best average value. The whole thing is
//! time-boxed with [`std::time::Instant`]: when the budget is exhausted we stop
//! sampling and return the best estimate so far, so a slow CPU degrades to fewer
//! simulations rather than hanging.

use std::time::{Duration, Instant};

use rand::rngs::StdRng;
use rand::{Rng, SeedableRng};

use shengji_mechanics::types::{Card, PlayerID};

use crate::bot::determinize::sample_hidden_hands;
use crate::bot::heuristics::{self, ScoredPlay};
use crate::game_state::play_phase::PlayPhase;

/// Tunable search parameters.
#[derive(Clone, Copy, Debug)]
pub struct SearchConfig {
    /// Wall-clock budget for a single decision.
    pub time_budget: Duration,
    /// Maximum number of candidate moves to evaluate (top-K by heuristic).
    pub max_candidates: usize,
    /// Maximum number of determinized worlds to sample per decision.
    pub max_worlds: usize,
    /// How many tricks (× players) of look-ahead each rollout plays before the
    /// static evaluation. Deeper rollouts give a more accurate value at higher
    /// cost.
    pub rollout_tricks: usize,
    /// RNG seed (lets the eval harness make runs reproducible).
    pub seed: u64,
}

impl Default for SearchConfig {
    fn default() -> Self {
        SearchConfig {
            time_budget: Duration::from_millis(1000),
            max_candidates: 6,
            max_worlds: 40,
            rollout_tricks: 6,
            seed: 0xC0FFEE,
        }
    }
}

/// Run the determinized search and return the chosen cards, or `None` if no
/// candidate could be produced (caller should fall back to the heuristic /
/// dumb policy).
pub fn search_play(p: &PlayPhase, me: PlayerID, config: SearchConfig) -> Option<Vec<Card>> {
    let leading = p.trick().played_cards().is_empty();

    // Candidate generation + heuristic pruning: take the top-K candidates.
    let mut candidates: Vec<ScoredPlay> = if leading {
        heuristics::ranked_leads(p, me)
    } else {
        heuristics::ranked_follows(p, me)
    };
    if candidates.is_empty() {
        return None;
    }
    candidates.truncate(config.max_candidates.max(1));

    // If there's only one candidate, no need to search.
    if candidates.len() == 1 {
        return Some(candidates.remove(0).cards);
    }

    let mut rng = StdRng::seed_from_u64(config.seed);

    let mut totals = vec![0.0f64; candidates.len()];
    let mut counts = vec![0u32; candidates.len()];

    let start = Instant::now();
    let mut worlds_done = 0;

    'outer: while worlds_done < config.max_worlds {
        if start.elapsed() >= config.time_budget {
            break;
        }
        // Sample one world; reuse it across all candidates for a fair, paired
        // comparison (variance reduction).
        let world = match sample_hidden_hands(p, me, &mut rng) {
            Some(w) => w,
            None => {
                worlds_done += 1;
                continue;
            }
        };

        for (idx, cand) in candidates.iter().enumerate() {
            // Periodically re-check the time budget so a heavy world can't blow
            // the cap.
            if start.elapsed() >= config.time_budget {
                break 'outer;
            }
            let value = evaluate_candidate(
                &world.play,
                me,
                &cand.cards,
                config.rollout_tricks,
                &mut rng,
            );
            if let Some(v) = value {
                totals[idx] += v;
                counts[idx] += 1;
            }
        }
        worlds_done += 1;
    }

    // Pick the candidate with the best average value; break ties toward the
    // higher heuristic score (candidates are already heuristic-sorted, so the
    // earliest index wins ties).
    let mut best_idx = 0;
    let mut best_avg = f64::NEG_INFINITY;
    for idx in 0..candidates.len() {
        let avg = if counts[idx] > 0 {
            totals[idx] / counts[idx] as f64
        } else {
            // No simulations ran for this candidate; fall back to its heuristic
            // score so it isn't unfairly ignored.
            candidates[idx].score
        };
        if avg > best_avg {
            best_avg = avg;
            best_idx = idx;
        }
    }

    Some(candidates[best_idx].cards.clone())
}

/// Run a PERFECT-INFORMATION search and return the chosen cards, or `None` if no
/// candidate could be produced (caller should fall back to the heuristic / dumb
/// policy).
///
/// # Perfect information (Omniscient cheater tier ONLY)
///
/// Unlike [`search_play`], this does NOT sample hidden hands. The play phase `p`
/// passed in is the TRUE world — every seat's real cards — because it was
/// obtained for an `Omniscient` bot via the centralized honesty bypass
/// ([`crate::bot::observed_state`]). We therefore evaluate every candidate
/// against that single known world using full (un-truncated) rollouts, with no
/// ε-noise and no softmax temperature (greedy on the search value). This reuses
/// exactly the same machinery ([`evaluate_candidate`] → [`rollout`] →
/// [`evaluate_position`]) as the honest Hard search; only the world source
/// differs (one true world vs. many sampled worlds).
///
/// This is the only search entry point that reads the real opponents' hands, and
/// it is reachable solely through the `Omniscient` dispatch in
/// [`crate::bot::policy`].
pub fn search_play_perfect_info(
    p: &PlayPhase,
    me: PlayerID,
    config: SearchConfig,
) -> Option<Vec<Card>> {
    let leading = p.trick().played_cards().is_empty();

    let mut candidates: Vec<ScoredPlay> = if leading {
        heuristics::ranked_leads(p, me)
    } else {
        heuristics::ranked_follows(p, me)
    };
    if candidates.is_empty() {
        return None;
    }
    candidates.truncate(config.max_candidates.max(1));
    if candidates.len() == 1 {
        return Some(candidates.remove(0).cards);
    }

    let mut rng = StdRng::seed_from_u64(config.seed);

    // Evaluate each candidate against the SINGLE true world `p`. We can run a few
    // rollouts per candidate (the rollout policy carries a little noise, so
    // averaging a handful reduces variance) within the time budget, then pick the
    // best mean value greedily (no ε, no temperature).
    let start = Instant::now();
    let mut best_idx = 0;
    let mut best_avg = f64::NEG_INFINITY;
    for (idx, cand) in candidates.iter().enumerate() {
        let mut total = 0.0f64;
        let mut count = 0u32;
        for _ in 0..config.max_worlds.max(1) {
            if start.elapsed() >= config.time_budget {
                break;
            }
            if let Some(v) = evaluate_candidate(p, me, &cand.cards, config.rollout_tricks, &mut rng)
            {
                total += v;
                count += 1;
            }
        }
        let avg = if count > 0 {
            total / count as f64
        } else {
            cand.score
        };
        if avg > best_avg {
            best_avg = avg;
            best_idx = idx;
        }
    }

    Some(candidates[best_idx].cards.clone())
}

/// Apply `cards` for `me` in a clone of `world`, then roll the rest of the
/// position out greedily with the heuristic and return the position value from
/// `me`'s team's perspective. Returns `None` if the candidate is somehow
/// illegal in this world (it should be legal, since it was generated from the
/// redacted hand, which is a subset of this world).
fn evaluate_candidate(
    world: &PlayPhase,
    me: PlayerID,
    cards: &[Card],
    rollout_tricks: usize,
    rng: &mut StdRng,
) -> Option<f64> {
    let mut sim = world.clone();
    // Play our candidate.
    if sim.play_cards(me, cards).is_err() {
        return None;
    }

    // Roll out a bounded number of tricks with the heuristic as every seat's
    // policy, then statically evaluate. Deeper look-ahead (`rollout_tricks`)
    // yields a more accurate value at higher cost; the static evaluator credits
    // the trick-winning potential still in our hand so we don't have to play
    // every card to value the position.
    let players = sim.propagated().players().len();
    // `saturating_mul` so a `rollout_tricks` of `usize::MAX` (the Omniscient
    // "roll out the whole hand" sentinel) caps at `usize::MAX` plies instead of
    // overflowing; the rollout loop terminates anyway once the hand is finished.
    let max_plies = players.saturating_mul(rollout_tricks.max(1));
    rollout(&mut sim, max_plies, rng);

    Some(evaluate_position(&sim, me))
}

/// Greedily roll the play-phase forward using the heuristic policy for whichever
/// seat is to act, finishing tricks as needed, for up to `max_plies` card
/// plays. Mutates `sim` in place.
fn rollout(sim: &mut PlayPhase, max_plies: usize, rng: &mut StdRng) {
    use rand::seq::SliceRandom;

    let mut plies = 0;
    while plies < max_plies {
        if sim.game_finished() {
            break;
        }
        match sim.trick().next_player() {
            None => {
                // Trick complete: finish it (winner leads next).
                if sim.finish_trick().is_err() {
                    break;
                }
            }
            Some(actor) => {
                let leading = sim.trick().played_cards().is_empty();
                let mut ranked = if leading {
                    heuristics::ranked_leads(sim, actor)
                } else {
                    heuristics::ranked_follows(sim, actor)
                };
                if ranked.is_empty() {
                    break;
                }
                // Use the heuristic-best move, with a small amount of noise so
                // rollouts explore (paired worlds already share the deal).
                let pick = if ranked.len() > 1 && rng.gen_bool(0.15) {
                    // occasionally take the 2nd-best to add variance
                    ranked.remove(1)
                } else {
                    ranked.remove(0)
                };
                let mut cards = pick.cards;
                // Defensive: if the heuristic play is somehow illegal in this
                // determinized world, fall back to any legal candidate.
                if sim.play_cards(actor, &cards).is_err() {
                    // Try other candidates.
                    let alts = if leading {
                        heuristics::lead_candidates(sim, actor)
                    } else {
                        heuristics::follow_candidates(sim, actor)
                    };
                    let mut ok = false;
                    let mut alts = alts;
                    alts.shuffle(rng);
                    for alt in alts {
                        if sim.play_cards(actor, &alt).is_ok() {
                            cards = alt;
                            ok = true;
                            break;
                        }
                    }
                    if !ok {
                        break;
                    }
                }
                let _ = cards;
                plies += 1;
            }
        }
    }
}

/// Static evaluation of a play-phase position from `me`'s team's perspective.
///
/// Combines the realized point differential so far (the non-landlord point total
/// is what the scoring engine ultimately uses) with a positional term crediting
/// the *trick-winning potential* still in our hand. Because rollouts are
/// shallow, the positional term is what lets the search prefer plays that
/// preserve our ability to capture future point tricks rather than only chasing
/// immediate points.
fn evaluate_position(sim: &PlayPhase, me: PlayerID) -> f64 {
    use shengji_mechanics::types::{Card, EffectiveSuit, Number};

    let team = sim.landlords_team();
    let me_is_landlord_team = team.contains(&me);

    // `calculate_points` returns (non_landlord_points, observed). The defending
    // (landlord) team wants non_landlord_points LOW; the attacking team wants it
    // HIGH. We orient the score so HIGHER is always better for `me`'s team.
    let (non_landlord_points, _) = sim.calculate_points();
    let realized = if me_is_landlord_team {
        -(non_landlord_points as f64)
    } else {
        non_landlord_points as f64
    };

    // Positional control: high cards and trumps remaining in our own hand are
    // future trick winners. Value them so the search keeps control rather than
    // dumping winners prematurely.
    let trump = sim.trump();
    let control = sim
        .hands()
        .get(me)
        .map(|h| {
            let mut v = 0.0;
            for (card, &ct) in h.iter() {
                let c = *card;
                let is_trump = trump.effective_suit(c) == EffectiveSuit::Trump;
                let mut w = 0.0;
                match c {
                    Card::BigJoker | Card::SmallJoker => w = 1.6,
                    Card::Suited { number, .. } => {
                        if is_trump {
                            w = 0.8;
                        } else if number == Number::Ace {
                            w = 1.0;
                        } else if number == Number::King {
                            w = 0.5;
                        }
                    }
                    Card::Unknown => {}
                }
                v += w * ct as f64;
            }
            v
        })
        .unwrap_or(0.0);

    realized + control
}
